import type { AoEmojiCategory, AoEmojiItem } from './types';

type Row = [char: string, name: string, ...keywords: string[]];

function rowsToItems(categoryId: string, rows: Row[]): AoEmojiItem[] {
  return rows.map(([char, name, ...keywords]) => ({
    id: char,
    char,
    name,
    keywords: [name, ...keywords].map((k) => k.toLowerCase()),
    categoryId,
    type: 'unicode' as const,
  }));
}

const SMILEYS: Row[] = [
  ['😀', 'grinning face', 'smile', 'happy', 'grin'],
  ['😃', 'grinning face with big eyes', 'smile', 'happy', 'joy'],
  ['😄', 'grinning face with smiling eyes', 'smile', 'happy', 'laugh'],
  ['😁', 'beaming face with smiling eyes', 'smile', 'grin'],
  ['😆', 'grinning squinting face', 'laugh', 'happy', 'haha'],
  ['😅', 'grinning face with sweat', 'laugh', 'relief', 'sweat'],
  ['🤣', 'rolling on the floor laughing', 'laugh', 'lol', 'rofl'],
  ['😂', 'face with tears of joy', 'laugh', 'cry', 'lol', 'joy'],
  ['🙂', 'slightly smiling face', 'smile'],
  ['😊', 'smiling face with smiling eyes', 'smile', 'blush', 'happy'],
  ['😇', 'smiling face with halo', 'angel', 'innocent'],
  ['😉', 'winking face', 'wink', 'flirt'],
  ['😌', 'relieved face', 'peace', 'calm'],
  ['😍', 'smiling face with heart-eyes', 'love', 'heart', 'crush'],
  ['🥰', 'smiling face with hearts', 'love', 'adore'],
  ['😘', 'face blowing a kiss', 'kiss', 'love'],
  ['😗', 'kissing face', 'kiss'],
  ['😙', 'kissing face with smiling eyes', 'kiss'],
  ['😚', 'kissing face with closed eyes', 'kiss'],
  ['😋', 'face savoring food', 'yum', 'tasty'],
  ['😛', 'face with tongue', 'tongue', 'playful'],
  ['😜', 'winking face with tongue', 'wink', 'prank'],
  ['🤪', 'zany face', 'goofy', 'crazy'],
  ['😝', 'squinting face with tongue', 'tongue', 'playful'],
  ['🤑', 'money-mouth face', 'money', 'rich'],
  ['🤗', 'smiling face with open hands', 'hug', 'happy'],
  ['🤭', 'face with hand over mouth', 'oops', 'quiet'],
  ['🤫', 'shushing face', 'quiet', 'secret'],
  ['🤔', 'thinking face', 'think', 'hmm'],
  ['🤐', 'zipper-mouth face', 'silent', 'secret'],
  ['🤨', 'face with raised eyebrow', 'suspicious', 'skeptic'],
  ['😐', 'neutral face', 'meh'],
  ['😑', 'expressionless face', 'blank'],
  ['😶', 'face without mouth', 'silent'],
  ['😏', 'smirking face', 'smirk', 'smug'],
  ['😒', 'unamused face', 'meh', 'sideeye'],
  ['🙄', 'face with rolling eyes', 'eyeroll'],
  ['😬', 'grimacing face', 'awkward'],
  ['🤥', 'lying face', 'lie', 'pinocchio'],
  ['😔', 'pensive face', 'sad', 'thoughtful'],
  ['😪', 'sleepy face', 'tired', 'sleep'],
  ['🤤', 'drooling face', 'hungry', 'desire'],
  ['😴', 'sleeping face', 'sleep', 'zzz'],
  ['😷', 'face with medical mask', 'sick', 'mask'],
  ['🤒', 'face with thermometer', 'sick', 'fever'],
  ['🤕', 'face with head-bandage', 'hurt', 'injured'],
  ['🤢', 'nauseated face', 'sick', 'gross'],
  ['🤮', 'face vomiting', 'sick', 'puke'],
  ['🤧', 'sneezing face', 'sick', 'sneeze'],
  ['🥵', 'hot face', 'hot', 'heat'],
  ['🥶', 'cold face', 'cold', 'freeze'],
  ['🥴', 'woozy face', 'drunk', 'dizzy'],
  ['😵', 'face with crossed-out eyes', 'dizzy', 'dead'],
  ['🤯', 'exploding head', 'mindblown', 'shock'],
  ['🤠', 'cowboy hat face', 'cowboy'],
  ['🥳', 'partying face', 'party', 'celebrate'],
  ['😎', 'smiling face with sunglasses', 'cool', 'sunglasses'],
  ['🤓', 'nerd face', 'nerd', 'geek'],
  ['🧐', 'face with monocle', 'inspect', 'curious'],
  ['😕', 'confused face', 'confused'],
  ['😟', 'worried face', 'worry'],
  ['🙁', 'slightly frowning face', 'sad', 'frown'],
  ['☹️', 'frowning face', 'sad', 'frown'],
  ['😮', 'face with open mouth', 'surprise', 'wow'],
  ['😯', 'hushed face', 'surprise'],
  ['😲', 'astonished face', 'shock', 'wow'],
  ['😳', 'flushed face', 'embarrassed', 'blush'],
  ['🥺', 'pleading face', 'please', 'puppy'],
  ['😦', 'frowning face with open mouth', 'sad'],
  ['😧', 'anguished face', 'pain'],
  ['😨', 'fearful face', 'fear', 'scared'],
  ['😰', 'anxious face with sweat', 'nervous', 'worry'],
  ['😥', 'sad but relieved face', 'sad', 'relief'],
  ['😢', 'crying face', 'cry', 'sad', 'tear'],
  ['😭', 'loudly crying face', 'cry', 'sob', 'sad'],
  ['😱', 'face screaming in fear', 'scream', 'fear'],
  ['😖', 'confounded face', 'frustrated'],
  ['😣', 'persevering face', 'struggle'],
  ['😞', 'disappointed face', 'sad', 'disappointed'],
  ['😓', 'downcast face with sweat', 'sad', 'sweat'],
  ['😩', 'weary face', 'tired', 'sad'],
  ['😫', 'tired face', 'tired'],
  ['🥱', 'yawning face', 'tired', 'yawn', 'bored'],
  ['😤', 'face with steam from nose', 'angry', 'huff'],
  ['😡', 'pouting face', 'angry', 'mad', 'rage'],
  ['😠', 'angry face', 'angry', 'mad'],
  ['🤬', 'face with symbols on mouth', 'swearing', 'mad'],
  ['😈', 'smiling face with horns', 'devil', 'evil'],
  ['👿', 'angry face with horns', 'devil', 'angry'],
  ['💀', 'skull', 'dead', 'skull'],
  ['☠️', 'skull and crossbones', 'dead', 'danger'],
  ['💩', 'pile of poo', 'poop', 'poo'],
  ['🤡', 'clown face', 'clown'],
  ['👹', 'ogre', 'monster'],
  ['👺', 'goblin', 'monster'],
  ['👻', 'ghost', 'halloween'],
  ['👽', 'alien', 'ufo'],
  ['👾', 'alien monster', 'game', 'space'],
  ['🤖', 'robot', 'bot'],
  ['😺', 'grinning cat', 'cat', 'smile'],
  ['😸', 'grinning cat with smiling eyes', 'cat'],
  ['😹', 'cat with tears of joy', 'cat', 'laugh'],
  ['😻', 'smiling cat with heart-eyes', 'cat', 'love'],
  ['😼', 'cat with wry smile', 'cat'],
  ['😽', 'kissing cat', 'cat', 'kiss'],
  ['🙀', 'weary cat', 'cat', 'shock'],
  ['😿', 'crying cat', 'cat', 'sad'],
  ['😾', 'pouting cat', 'cat', 'angry'],
];

const PEOPLE: Row[] = [
  ['👋', 'waving hand', 'wave', 'hello', 'hi', 'bye'],
  ['🤚', 'raised back of hand', 'hand'],
  ['🖐', 'hand with fingers splayed', 'hand'],
  ['✋', 'raised hand', 'hand', 'stop'],
  ['🖖', 'vulcan salute', 'spock', 'hand'],
  ['👌', 'OK hand', 'ok', 'perfect'],
  ['🤌', 'pinched fingers', 'italian', 'hand'],
  ['🤏', 'pinching hand', 'small', 'hand'],
  ['✌️', 'victory hand', 'peace', 'v'],
  ['🤞', 'crossed fingers', 'luck', 'hope'],
  ['🤟', 'love-you gesture', 'love', 'ily'],
  ['🤘', 'sign of the horns', 'rock', 'metal'],
  ['🤙', 'call me hand', 'call', 'shaka'],
  ['👈', 'backhand index pointing left', 'left', 'point'],
  ['👉', 'backhand index pointing right', 'right', 'point'],
  ['👆', 'backhand index pointing up', 'up', 'point'],
  ['🖕', 'middle finger', 'rude'],
  ['👇', 'backhand index pointing down', 'down', 'point'],
  ['☝️', 'index pointing up', 'up', 'point'],
  ['👍', 'thumbs up', 'like', 'yes', 'approve', 'good'],
  ['👎', 'thumbs down', 'dislike', 'no', 'bad'],
  ['✊', 'raised fist', 'fist', 'power'],
  ['👊', 'oncoming fist', 'punch', 'fist'],
  ['🤛', 'left-facing fist', 'fist'],
  ['🤜', 'right-facing fist', 'fist'],
  ['👏', 'clapping hands', 'clap', 'applause', 'bravo'],
  ['🙌', 'raising hands', 'hooray', 'celebration'],
  ['👐', 'open hands', 'hands'],
  ['🤲', 'palms up together', 'pray', 'hands'],
  ['🤝', 'handshake', 'deal', 'agree'],
  ['🙏', 'folded hands', 'pray', 'please', 'thanks', 'namaste'],
  ['💪', 'flexed biceps', 'strong', 'muscle', 'flex'],
  ['🦾', 'mechanical arm', 'robot', 'prosthetic'],
  ['🦿', 'mechanical leg', 'robot', 'prosthetic'],
  ['🦵', 'leg', 'kick'],
  ['🦶', 'foot', 'kick'],
  ['👂', 'ear', 'hear'],
  ['🦻', 'ear with hearing aid', 'hear'],
  ['👃', 'nose', 'smell'],
  ['🧠', 'brain', 'smart', 'think'],
  ['👀', 'eyes', 'look', 'see'],
  ['👁', 'eye', 'look'],
  ['👅', 'tongue', 'taste'],
  ['👄', 'mouth', 'lips'],
  ['👶', 'baby', 'infant'],
  ['🧒', 'child', 'kid'],
  ['👦', 'boy', 'male'],
  ['👧', 'girl', 'female'],
  ['🧑', 'person', 'adult'],
  ['👱', 'person blond hair', 'blond'],
  ['👨', 'man', 'male'],
  ['👩', 'woman', 'female'],
  ['🧓', 'older person', 'elder'],
  ['👴', 'old man', 'elder'],
  ['👵', 'old woman', 'elder'],
  ['🙍', 'person frowning', 'sad'],
  ['🙎', 'person pouting', 'upset'],
  ['🙅', 'person gesturing NO', 'no', 'stop'],
  ['🙆', 'person gesturing OK', 'ok'],
  ['💁', 'person tipping hand', 'info', 'sassy'],
  ['🙋', 'person raising hand', 'question', 'raise'],
  ['🧏', 'deaf person', 'deaf'],
  ['🙇', 'person bowing', 'sorry', 'bow'],
  ['🤦', 'person facepalming', 'facepalm', 'dumb'],
  ['🤷', 'person shrugging', 'shrug', 'idk'],
  ['👮', 'police officer', 'cop', 'police'],
  ['🕵️', 'detective', 'spy'],
  ['💂', 'guard', 'britain'],
  ['🥷', 'ninja', 'stealth'],
  ['👷', 'construction worker', 'builder'],
  ['🤴', 'prince', 'royalty'],
  ['👸', 'princess', 'royalty'],
  ['🦸', 'superhero', 'hero'],
  ['🦹', 'supervillain', 'villain'],
  ['🧙', 'mage', 'wizard', 'magic'],
  ['🧚', 'fairy', 'magic'],
  ['🧛', 'vampire', 'dracula'],
  ['🧜', 'merperson', 'mermaid'],
  ['🧝', 'elf', 'fantasy'],
  ['🧞', 'genie', 'wish'],
  ['🧟', 'zombie', 'undead'],
  ['💆', 'person getting massage', 'spa'],
  ['💇', 'person getting haircut', 'hair'],
  ['🚶', 'person walking', 'walk'],
  ['🧍', 'person standing', 'stand'],
  ['🧎', 'person kneeling', 'kneel'],
  ['🏃', 'person running', 'run', 'jog'],
  ['💃', 'woman dancing', 'dance'],
  ['🕺', 'man dancing', 'dance'],
  ['👯', 'people with bunny ears', 'party', 'dance'],
  ['🧖', 'person in steamy room', 'sauna'],
  ['🧗', 'person climbing', 'climb'],
  ['🧘', 'person in lotus position', 'yoga', 'meditate'],
  ['🛀', 'person taking bath', 'bath'],
  ['🛌', 'person in bed', 'sleep'],
];

const ANIMALS: Row[] = [
  ['🐶', 'dog face', 'dog', 'puppy', 'pet'],
  ['🐱', 'cat face', 'cat', 'kitten', 'pet'],
  ['🐭', 'mouse face', 'mouse'],
  ['🐹', 'hamster', 'pet'],
  ['🐰', 'rabbit face', 'bunny', 'rabbit'],
  ['🦊', 'fox', 'animal'],
  ['🐻', 'bear', 'animal'],
  ['🐼', 'panda', 'bear'],
  ['🐨', 'koala', 'animal'],
  ['🐯', 'tiger face', 'tiger'],
  ['🦁', 'lion', 'animal'],
  ['🐮', 'cow face', 'cow'],
  ['🐷', 'pig face', 'pig'],
  ['🐸', 'frog', 'animal'],
  ['🐵', 'monkey face', 'monkey'],
  ['🙈', 'see-no-evil monkey', 'monkey', 'see'],
  ['🙉', 'hear-no-evil monkey', 'monkey', 'hear'],
  ['🙊', 'speak-no-evil monkey', 'monkey', 'speak'],
  ['🐒', 'monkey', 'animal'],
  ['🐔', 'chicken', 'bird'],
  ['🐧', 'penguin', 'bird'],
  ['🐦', 'bird', 'animal'],
  ['🐤', 'baby chick', 'chick', 'bird'],
  ['🐣', 'hatching chick', 'chick', 'bird'],
  ['🐥', 'front-facing baby chick', 'chick'],
  ['🦆', 'duck', 'bird'],
  ['🦅', 'eagle', 'bird'],
  ['🦉', 'owl', 'bird'],
  ['🦇', 'bat', 'animal'],
  ['🐺', 'wolf', 'animal'],
  ['🐗', 'boar', 'pig'],
  ['🐴', 'horse face', 'horse'],
  ['🦄', 'unicorn', 'fantasy'],
  ['🐝', 'honeybee', 'bee', 'insect'],
  ['🐛', 'bug', 'insect'],
  ['🦋', 'butterfly', 'insect'],
  ['🐌', 'snail', 'slow'],
  ['🐞', 'lady beetle', 'bug', 'insect'],
  ['🐜', 'ant', 'insect'],
  ['🦟', 'mosquito', 'insect'],
  ['🦗', 'cricket', 'insect'],
  ['🕷', 'spider', 'insect'],
  ['🕸', 'spider web', 'web'],
  ['🐢', 'turtle', 'animal'],
  ['🐍', 'snake', 'animal'],
  ['🦎', 'lizard', 'animal'],
  ['🦖', 'T-Rex', 'dinosaur'],
  ['🦕', 'sauropod', 'dinosaur'],
  ['🐙', 'octopus', 'sea'],
  ['🦑', 'squid', 'sea'],
  ['🦐', 'shrimp', 'sea'],
  ['🦞', 'lobster', 'sea'],
  ['🦀', 'crab', 'sea'],
  ['🐡', 'blowfish', 'fish'],
  ['🐠', 'tropical fish', 'fish'],
  ['🐟', 'fish', 'sea'],
  ['🐬', 'dolphin', 'sea'],
  ['🐳', 'spouting whale', 'whale'],
  ['🐋', 'whale', 'sea'],
  ['🦈', 'shark', 'sea'],
  ['🐊', 'crocodile', 'animal'],
  ['🐅', 'tiger', 'animal'],
  ['🐆', 'leopard', 'animal'],
  ['🦓', 'zebra', 'animal'],
  ['🦍', 'gorilla', 'ape'],
  ['🦧', 'orangutan', 'ape'],
  ['🐘', 'elephant', 'animal'],
  ['🦛', 'hippopotamus', 'hippo'],
  ['🦏', 'rhinoceros', 'rhino'],
  ['🐪', 'camel', 'desert'],
  ['🐫', 'two-hump camel', 'camel'],
  ['🦒', 'giraffe', 'animal'],
  ['🦘', 'kangaroo', 'animal'],
  ['🦬', 'bison', 'animal'],
  ['🐃', 'water buffalo', 'buffalo'],
  ['🐂', 'ox', 'bull'],
  ['🐄', 'cow', 'animal'],
  ['🐎', 'horse', 'animal'],
  ['🐖', 'pig', 'animal'],
  ['🐏', 'ram', 'sheep'],
  ['🐑', 'ewe', 'sheep'],
  ['🦙', 'llama', 'animal'],
  ['🐐', 'goat', 'animal'],
  ['🦌', 'deer', 'animal'],
  ['🐕', 'dog', 'pet'],
  ['🐩', 'poodle', 'dog'],
  ['🦮', 'guide dog', 'dog'],
  ['🐈', 'cat', 'pet'],
  ['🪶', 'feather', 'bird'],
  ['🐓', 'rooster', 'chicken'],
  ['🦃', 'turkey', 'bird'],
  ['🦤', 'dodo', 'bird'],
  ['🦚', 'peacock', 'bird'],
  ['🦜', 'parrot', 'bird'],
  ['🦢', 'swan', 'bird'],
  ['🦩', 'flamingo', 'bird'],
  ['🕊', 'dove', 'peace', 'bird'],
  ['🐇', 'rabbit', 'bunny'],
  ['🦝', 'raccoon', 'animal'],
  ['🦨', 'skunk', 'animal'],
  ['🦡', 'badger', 'animal'],
  ['🦫', 'beaver', 'animal'],
  ['🦦', 'otter', 'animal'],
  ['🦥', 'sloth', 'slow'],
  ['🐁', 'mouse', 'animal'],
  ['🐀', 'rat', 'animal'],
  ['🐿', 'chipmunk', 'animal'],
  ['🦔', 'hedgehog', 'animal'],
  ['🐾', 'paw prints', 'paw', 'pet'],
  ['🐉', 'dragon', 'fantasy'],
  ['🐲', 'dragon face', 'fantasy'],
  ['🌵', 'cactus', 'plant', 'desert'],
  ['🎄', 'Christmas tree', 'tree', 'christmas'],
  ['🌲', 'evergreen tree', 'tree'],
  ['🌳', 'deciduous tree', 'tree'],
  ['🌴', 'palm tree', 'tree', 'beach'],
  ['🌱', 'seedling', 'plant', 'grow'],
  ['🌿', 'herb', 'plant', 'leaf'],
  ['☘️', 'shamrock', 'luck', 'leaf'],
  ['🍀', 'four leaf clover', 'luck', 'clover'],
  ['🍁', 'maple leaf', 'leaf', 'fall'],
  ['🍂', 'fallen leaf', 'leaf', 'fall'],
  ['🍃', 'leaf fluttering in wind', 'leaf'],
  ['🍄', 'mushroom', 'fungus'],
  ['🐚', 'spiral shell', 'shell', 'beach'],
  ['🪸', 'coral', 'sea'],
  ['🪨', 'rock', 'stone'],
  ['🌎', 'globe Americas', 'earth', 'world', 'globe'],
  ['🌍', 'globe Europe-Africa', 'earth', 'world', 'globe'],
  ['🌏', 'globe Asia-Australia', 'earth', 'world', 'globe'],
  ['🌐', 'globe with meridians', 'earth', 'world', 'internet'],
  ['🌑', 'new moon', 'moon'],
  ['🌒', 'waxing crescent moon', 'moon'],
  ['🌓', 'first quarter moon', 'moon'],
  ['🌔', 'waxing gibbous moon', 'moon'],
  ['🌕', 'full moon', 'moon'],
  ['🌖', 'waning gibbous moon', 'moon'],
  ['🌗', 'last quarter moon', 'moon'],
  ['🌘', 'waning crescent moon', 'moon'],
  ['🌙', 'crescent moon', 'moon', 'night'],
  ['🌚', 'new moon face', 'moon'],
  ['🌝', 'full moon face', 'moon'],
  ['🌞', 'sun with face', 'sun'],
  ['⭐', 'star', 'star'],
  ['🌟', 'glowing star', 'star', 'shine'],
  ['✨', 'sparkles', 'sparkle', 'magic', 'shine'],
  ['⚡', 'high voltage', 'lightning', 'zap', 'electric'],
  ['🔥', 'fire', 'hot', 'lit', 'flame'],
  ['💧', 'droplet', 'water', 'drop'],
  ['🌊', 'water wave', 'ocean', 'sea', 'wave'],
];

const FOOD: Row[] = [
  ['🍏', 'green apple', 'apple', 'fruit'],
  ['🍎', 'red apple', 'apple', 'fruit'],
  ['🍐', 'pear', 'fruit'],
  ['🍊', 'tangerine', 'orange', 'fruit'],
  ['🍋', 'lemon', 'fruit'],
  ['🍌', 'banana', 'fruit'],
  ['🍉', 'watermelon', 'fruit'],
  ['🍇', 'grapes', 'fruit'],
  ['🍓', 'strawberry', 'fruit', 'berry'],
  ['🫐', 'blueberries', 'fruit', 'berry'],
  ['🍈', 'melon', 'fruit'],
  ['🍒', 'cherries', 'fruit'],
  ['🍑', 'peach', 'fruit'],
  ['🥭', 'mango', 'fruit'],
  ['🍍', 'pineapple', 'fruit'],
  ['🥥', 'coconut', 'fruit'],
  ['🥝', 'kiwi fruit', 'fruit'],
  ['🍅', 'tomato', 'veggie'],
  ['🍆', 'eggplant', 'veggie'],
  ['🥑', 'avocado', 'fruit'],
  ['🥦', 'broccoli', 'veggie'],
  ['🥬', 'leafy green', 'veggie', 'salad'],
  ['🥒', 'cucumber', 'veggie'],
  ['🌶', 'hot pepper', 'spicy', 'chili'],
  ['🫑', 'bell pepper', 'veggie'],
  ['🌽', 'ear of corn', 'corn'],
  ['🥕', 'carrot', 'veggie'],
  ['🫒', 'olive', 'food'],
  ['🧄', 'garlic', 'food'],
  ['🧅', 'onion', 'food'],
  ['🥔', 'potato', 'veggie'],
  ['🍠', 'roasted sweet potato', 'potato'],
  ['🥐', 'croissant', 'bread', 'bakery'],
  ['🥯', 'bagel', 'bread'],
  ['🍞', 'bread', 'toast'],
  ['🥖', 'baguette bread', 'bread'],
  ['🥨', 'pretzel', 'snack'],
  ['🧀', 'cheese wedge', 'cheese'],
  ['🥚', 'egg', 'food'],
  ['🍳', 'cooking', 'egg', 'fried'],
  ['🧈', 'butter', 'food'],
  ['🥞', 'pancakes', 'breakfast'],
  ['🧇', 'waffle', 'breakfast'],
  ['🥓', 'bacon', 'meat'],
  ['🥩', 'cut of meat', 'steak', 'meat'],
  ['🍗', 'poultry leg', 'chicken', 'meat'],
  ['🍖', 'meat on bone', 'meat'],
  ['🦴', 'bone', 'dog'],
  ['🌭', 'hot dog', 'food'],
  ['🍔', 'hamburger', 'burger', 'food'],
  ['🍟', 'french fries', 'fries', 'food'],
  ['🍕', 'pizza', 'food'],
  ['🫓', 'flatbread', 'food'],
  ['🥪', 'sandwich', 'food'],
  ['🥙', 'stuffed flatbread', 'food'],
  ['🧆', 'falafel', 'food'],
  ['🌮', 'taco', 'food'],
  ['🌯', 'burrito', 'food'],
  ['🫔', 'tamale', 'food'],
  ['🥗', 'green salad', 'salad'],
  ['🥘', 'shallow pan of food', 'paella', 'food'],
  ['🫕', 'fondue', 'food'],
  ['🥫', 'canned food', 'food'],
  ['🍝', 'spaghetti', 'pasta', 'noodles'],
  ['🍜', 'steaming bowl', 'ramen', 'noodles'],
  ['🍲', 'pot of food', 'stew'],
  ['🍛', 'curry rice', 'curry'],
  ['🍣', 'sushi', 'japanese'],
  ['🍱', 'bento box', 'japanese'],
  ['🥟', 'dumpling', 'food'],
  ['🦪', 'oyster', 'seafood'],
  ['🍤', 'fried shrimp', 'shrimp'],
  ['🍙', 'rice ball', 'rice'],
  ['🍚', 'cooked rice', 'rice'],
  ['🍘', 'rice cracker', 'rice'],
  ['🍥', 'fish cake with swirl', 'food'],
  ['🥠', 'fortune cookie', 'cookie'],
  ['🥮', 'moon cake', 'dessert'],
  ['🍢', 'oden', 'food'],
  ['🍡', 'dango', 'dessert'],
  ['🍧', 'shaved ice', 'dessert', 'ice'],
  ['🍨', 'ice cream', 'dessert'],
  ['🍦', 'soft ice cream', 'dessert'],
  ['🥧', 'pie', 'dessert'],
  ['🧁', 'cupcake', 'dessert', 'cake'],
  ['🍰', 'shortcake', 'cake', 'dessert'],
  ['🎂', 'birthday cake', 'cake', 'birthday', 'party'],
  ['🍮', 'custard', 'dessert'],
  ['🍭', 'lollipop', 'candy', 'sweet'],
  ['🍬', 'candy', 'sweet'],
  ['🍫', 'chocolate bar', 'chocolate', 'sweet'],
  ['🍿', 'popcorn', 'snack'],
  ['🍩', 'doughnut', 'donut', 'dessert'],
  ['🍪', 'cookie', 'dessert'],
  ['🌰', 'chestnut', 'nut'],
  ['🥜', 'peanuts', 'nut'],
  ['🍯', 'honey pot', 'honey'],
  ['🥛', 'glass of milk', 'milk', 'drink'],
  ['🍼', 'baby bottle', 'milk', 'baby'],
  ['☕️', 'hot beverage', 'coffee', 'tea', 'drink'],
  ['🍵', 'teacup without handle', 'tea', 'drink'],
  ['🧃', 'beverage box', 'juice', 'drink'],
  ['🥤', 'cup with straw', 'soda', 'drink'],
  ['🧋', 'bubble tea', 'boba', 'drink'],
  ['🍶', 'sake', 'drink', 'alcohol'],
  ['🍺', 'beer mug', 'beer', 'drink', 'alcohol'],
  ['🍻', 'clinking beer mugs', 'beer', 'cheers'],
  ['🥂', 'clinking glasses', 'cheers', 'celebrate'],
  ['🍷', 'wine glass', 'wine', 'drink'],
  ['🥃', 'tumbler glass', 'whiskey', 'drink'],
  ['🍸', 'cocktail glass', 'drink', 'alcohol'],
  ['🍹', 'tropical drink', 'cocktail'],
  ['🧉', 'mate', 'drink'],
  ['🍾', 'bottle with popping cork', 'champagne', 'celebrate'],
  ['🧊', 'ice', 'cold'],
  ['🥄', 'spoon', 'utensil'],
  ['🍴', 'fork and knife', 'eat', 'utensil'],
  ['🍽', 'fork and knife with plate', 'dinner'],
  ['🥣', 'bowl with spoon', 'cereal'],
  ['🥡', 'takeout box', 'food'],
  ['🥢', 'chopsticks', 'utensil'],
];

const TRAVEL: Row[] = [
  ['🚗', 'automobile', 'car', 'drive'],
  ['🚕', 'taxi', 'cab'],
  ['🚙', 'sport utility vehicle', 'car', 'suv'],
  ['🚌', 'bus', 'transit'],
  ['🚎', 'trolleybus', 'bus'],
  ['🏎', 'racing car', 'race'],
  ['🚓', 'police car', 'police'],
  ['🚑', 'ambulance', 'emergency'],
  ['🚒', 'fire engine', 'fire'],
  ['🚐', 'minibus', 'van'],
  ['🛻', 'pickup truck', 'truck'],
  ['🚚', 'delivery truck', 'truck'],
  ['🚛', 'articulated lorry', 'truck'],
  ['🚜', 'tractor', 'farm'],
  ['🛵', 'motor scooter', 'scooter'],
  ['🏍️', 'motorcycle', 'bike'],
  ['🛺', 'auto rickshaw', 'tuk tuk'],
  ['🚲', 'bicycle', 'bike', 'cycle'],
  ['🛴', 'kick scooter', 'scooter'],
  ['🚨', 'police car light', 'siren', 'emergency'],
  ['🚔', 'oncoming police car', 'police'],
  ['🚍', 'oncoming bus', 'bus'],
  ['🚘', 'oncoming automobile', 'car'],
  ['🚖', 'oncoming taxi', 'taxi'],
  ['🚡', 'aerial tramway', 'cable'],
  ['🚠', 'mountain cableway', 'cable'],
  ['🚟', 'suspension railway', 'train'],
  ['🚃', 'railway car', 'train'],
  ['🚋', 'tram car', 'tram'],
  ['🚞', 'mountain railway', 'train'],
  ['🚝', 'monorail', 'train'],
  ['🚄', 'high-speed train', 'train', 'bullet'],
  ['🚅', 'bullet train', 'train'],
  ['🚈', 'light rail', 'train'],
  ['🚂', 'locomotive', 'train'],
  ['🚆', 'train', 'rail'],
  ['🚇', 'metro', 'subway'],
  ['🚊', 'tram', 'transit'],
  ['🚉', 'station', 'train'],
  ['✈️', 'airplane', 'flight', 'travel', 'plane'],
  ['🛫', 'airplane departure', 'flight', 'takeoff'],
  ['🛬', 'airplane arrival', 'flight', 'landing'],
  ['🛩', 'small airplane', 'plane'],
  ['💺', 'seat', 'flight'],
  ['🛰', 'satellite', 'space'],
  ['🚀', 'rocket', 'space', 'launch'],
  ['🛸', 'flying saucer', 'ufo', 'alien'],
  ['🚁', 'helicopter', 'chopper'],
  ['🛶', 'canoe', 'boat'],
  ['⛵', 'sailboat', 'boat'],
  ['🚤', 'speedboat', 'boat'],
  ['🛥', 'motor boat', 'boat'],
  ['🚢', 'ship', 'boat', 'cruise'],
  ['⚓', 'anchor', 'ship'],
  ['⛽', 'fuel pump', 'gas'],
  ['🚧', 'construction', 'roadwork'],
  ['🚦', 'vertical traffic light', 'traffic'],
  ['🚥', 'horizontal traffic light', 'traffic'],
  ['🗺', 'world map', 'map', 'travel'],
  ['🗿', 'moai', 'statue'],
  ['🗽', 'Statue of Liberty', 'usa', 'new york'],
  ['🗼', 'Tokyo tower', 'japan'],
  ['🏰', 'castle', 'building'],
  ['🏯', 'Japanese castle', 'japan'],
  ['🏟', 'stadium', 'sports'],
  ['🎡', 'ferris wheel', 'fair'],
  ['🎢', 'roller coaster', 'fair'],
  ['🎠', 'carousel horse', 'fair'],
  ['⛲', 'fountain', 'park'],
  ['⛱', 'umbrella on ground', 'beach'],
  ['🏖', 'beach with umbrella', 'beach', 'vacation'],
  ['🏝', 'desert island', 'island', 'vacation'],
  ['🏜', 'desert', 'sand'],
  ['🌋', 'volcano', 'eruption'],
  ['⛰', 'mountain', 'hike'],
  ['🏔', 'snow-capped mountain', 'mountain'],
  ['🗻', 'mount fuji', 'japan', 'mountain'],
  ['🏕', 'camping', 'tent'],
  ['⛺', 'tent', 'camping'],
  ['🏠', 'house', 'home'],
  ['🏡', 'house with garden', 'home'],
  ['🏘', 'houses', 'home'],
  ['🏢', 'office building', 'work'],
  ['🏬', 'department store', 'shop'],
  ['🏣', 'Japanese post office', 'post'],
  ['🏤', 'post office', 'post'],
  ['🏥', 'hospital', 'health'],
  ['🏦', 'bank', 'money'],
  ['🏨', 'hotel', 'travel'],
  ['🏪', 'convenience store', 'shop'],
  ['🏫', 'school', 'education', 'university', 'campus'],
  ['🏩', 'love hotel', 'hotel'],
  ['💒', 'wedding', 'marriage'],
  ['🏛', 'classical building', 'museum'],
  ['⛪', 'church', 'religion'],
  ['🕌', 'mosque', 'religion'],
  ['🛕', 'hindu temple', 'religion'],
  ['🕍', 'synagogue', 'religion'],
  ['🕋', 'kaaba', 'religion'],
  ['⛩', 'shinto shrine', 'japan'],
  ['🌁', 'foggy', 'fog'],
  ['🌃', 'night with stars', 'night', 'city'],
  ['🏙', 'cityscape', 'city'],
  ['🌅', 'sunrise', 'morning', 'sun'],
  ['🌄', 'sunrise over mountains', 'sunrise'],
  ['🌆', 'cityscape at dusk', 'city', 'evening'],
  ['🌇', 'sunset', 'sun'],
  ['🌉', 'bridge at night', 'night'],
  ['♨️', 'hot springs', 'spa'],
  ['🎠', 'carousel horse', 'ride'],
  ['💈', 'barber pole', 'haircut'],
  ['🎪', 'circus tent', 'circus'],
];

const ACTIVITIES: Row[] = [
  ['⚽', 'soccer ball', 'football', 'soccer', 'sport'],
  ['🏀', 'basketball', 'sport'],
  ['🏈', 'american football', 'sport'],
  ['⚾', 'baseball', 'sport'],
  ['🥎', 'softball', 'sport'],
  ['🎾', 'tennis', 'sport'],
  ['🏐', 'volleyball', 'sport'],
  ['🏉', 'rugby football', 'sport'],
  ['🥏', 'flying disc', 'frisbee'],
  ['🎱', 'pool 8 ball', 'billiards'],
  ['🪀', 'yo-yo', 'toy'],
  ['🏓', 'ping pong', 'table tennis'],
  ['🏸', 'badminton', 'sport'],
  ['🏒', 'ice hockey', 'sport'],
  ['🏑', 'field hockey', 'sport'],
  ['🥍', 'lacrosse', 'sport'],
  ['🏏', 'cricket game', 'sport'],
  ['🪃', 'boomerang', 'sport'],
  ['🥅', 'goal net', 'sport'],
  ['⛳', 'flag in hole', 'golf'],
  ['🪁', 'kite', 'fly'],
  ['🏹', 'bow and arrow', 'archery'],
  ['🎣', 'fishing pole', 'fish'],
  ['🤿', 'diving mask', 'scuba'],
  ['🥊', 'boxing glove', 'box', 'fight'],
  ['🥋', 'martial arts uniform', 'karate'],
  ['🎽', 'running shirt', 'run'],
  ['🛹', 'skateboard', 'skate'],
  ['🛼', 'roller skate', 'skate'],
  ['🛷', 'sled', 'snow'],
  ['⛸', 'ice skate', 'skate'],
  ['🥌', 'curling stone', 'sport'],
  ['🎿', 'skis', 'ski', 'snow'],
  ['⛷', 'skier', 'ski'],
  ['🏂', 'snowboarder', 'snow'],
  ['🪂', 'parachute', 'skydiving'],
  ['🏋️', 'person lifting weights', 'gym', 'lift'],
  ['🤼', 'people wrestling', 'wrestle'],
  ['🤸', 'person cartwheeling', 'gymnastics'],
  ['⛹️', 'person bouncing ball', 'basketball'],
  ['🤺', 'person fencing', 'sword'],
  ['🤾', 'person playing handball', 'handball'],
  ['🏌️', 'person golfing', 'golf'],
  ['🏇', 'horse racing', 'race'],
  ['🧘', 'person in lotus position', 'yoga'],
  ['🏄', 'person surfing', 'surf'],
  ['🏊', 'person swimming', 'swim'],
  ['🤽', 'person playing water polo', 'polo'],
  ['🚣', 'person rowing boat', 'row'],
  ['🧗', 'person climbing', 'climb'],
  ['🚵', 'person mountain biking', 'bike'],
  ['🚴', 'person biking', 'bike'],
  ['🏆', 'trophy', 'win', 'award', 'champion'],
  ['🥇', '1st place medal', 'gold', 'medal', 'win'],
  ['🥈', '2nd place medal', 'silver', 'medal'],
  ['🥉', '3rd place medal', 'bronze', 'medal'],
  ['🏅', 'sports medal', 'medal'],
  ['🎖', 'military medal', 'medal'],
  ['🏵', 'rosette', 'award'],
  ['🎗', 'reminder ribbon', 'awareness'],
  ['🎫', 'ticket', 'event'],
  ['🎟', 'admission tickets', 'ticket'],
  ['🎪', 'circus tent', 'circus'],
  ['🤹', 'person juggling', 'juggle'],
  ['🎭', 'performing arts', 'theater', 'drama'],
  ['🩰', 'ballet shoes', 'dance'],
  ['🎨', 'artist palette', 'art', 'paint'],
  ['🎬', 'clapper board', 'movie', 'film'],
  ['🎤', 'microphone', 'sing', 'karaoke'],
  ['🎧', 'headphone', 'music', 'listen'],
  ['🎼', 'musical score', 'music'],
  ['🎹', 'musical keyboard', 'piano', 'music'],
  ['🥁', 'drum', 'music'],
  ['🪘', 'long drum', 'music'],
  ['🎷', 'saxophone', 'music'],
  ['🎺', 'trumpet', 'music'],
  ['🎸', 'guitar', 'music', 'rock'],
  ['🪕', 'banjo', 'music'],
  ['🎻', 'violin', 'music'],
  ['🎲', 'game die', 'dice', 'game'],
  ['♟', 'chess pawn', 'chess', 'game'],
  ['🎯', 'bullseye', 'target', 'direct'],
  ['🎳', 'bowling', 'game'],
  ['🎮', 'video game', 'game', 'controller'],
  ['🎰', 'slot machine', 'casino'],
  ['🧩', 'puzzle piece', 'puzzle'],
];

const OBJECTS: Row[] = [
  ['⌚', 'watch', 'time'],
  ['📱', 'mobile phone', 'phone', 'iphone'],
  ['📲', 'mobile phone with arrow', 'call'],
  ['💻', 'laptop', 'computer', 'pc'],
  ['⌨️', 'keyboard', 'computer'],
  ['🖥', 'desktop computer', 'computer'],
  ['🖨', 'printer', 'print'],
  ['🖱', 'computer mouse', 'mouse'],
  ['🕹', 'joystick', 'game'],
  ['🗜', 'clamp', 'tool'],
  ['💾', 'floppy disk', 'save'],
  ['💿', 'optical disk', 'cd'],
  ['📀', 'dvd', 'disk'],
  ['📷', 'camera', 'photo'],
  ['📸', 'camera with flash', 'photo'],
  ['📹', 'video camera', 'video'],
  ['🎥', 'movie camera', 'film'],
  ['📽', 'film projector', 'movie'],
  ['🎞', 'film frames', 'movie'],
  ['📞', 'telephone receiver', 'phone', 'call'],
  ['☎️', 'telephone', 'phone'],
  ['📟', 'pager', 'beeper'],
  ['📠', 'fax machine', 'fax'],
  ['📺', 'television', 'tv'],
  ['📻', 'radio', 'music'],
  ['🎙', 'studio microphone', 'mic'],
  ['⏱', 'stopwatch', 'timer'],
  ['⏲', 'timer clock', 'timer'],
  ['⏰', 'alarm clock', 'alarm', 'wake'],
  ['🕰', 'mantelpiece clock', 'clock'],
  ['⌛', 'hourglass done', 'time', 'wait'],
  ['⏳', 'hourglass not done', 'time', 'wait'],
  ['📡', 'satellite antenna', 'signal'],
  ['🔋', 'battery', 'power'],
  ['🔌', 'electric plug', 'power'],
  ['💡', 'light bulb', 'idea', 'light'],
  ['🔦', 'flashlight', 'light'],
  ['🕯', 'candle', 'light'],
  ['🧯', 'fire extinguisher', 'fire'],
  ['🛢', 'oil drum', 'oil'],
  ['💸', 'money with wings', 'money', 'spend'],
  ['💵', 'dollar banknote', 'money', 'dollar'],
  ['💴', 'yen banknote', 'money'],
  ['💶', 'euro banknote', 'money'],
  ['💷', 'pound banknote', 'money'],
  ['🪙', 'coin', 'money'],
  ['💰', 'money bag', 'money', 'rich'],
  ['💳', 'credit card', 'money', 'pay'],
  ['💎', 'gem stone', 'diamond', 'jewel'],
  ['⚖️', 'balance scale', 'justice', 'law'],
  ['🧰', 'toolbox', 'tools'],
  ['🔧', 'wrench', 'tool'],
  ['🔨', 'hammer', 'tool'],
  ['⚒', 'hammer and pick', 'tool'],
  ['🛠', 'hammer and wrench', 'tool'],
  ['⛏', 'pick', 'tool'],
  ['🔩', 'nut and bolt', 'tool'],
  ['⚙️', 'gear', 'settings'],
  ['🧱', 'brick', 'wall'],
  ['⛓', 'chains', 'link'],
  ['🧲', 'magnet', 'attract'],
  ['🔫', 'water pistol', 'gun', 'toy'],
  ['💣', 'bomb', 'explode'],
  ['🔪', 'kitchen knife', 'knife'],
  ['🗡', 'dagger', 'knife'],
  ['⚔️', 'crossed swords', 'fight'],
  ['🛡', 'shield', 'protect'],
  ['🚬', 'cigarette', 'smoke'],
  ['⚰️', 'coffin', 'dead'],
  ['🪦', 'headstone', 'grave'],
  ['⚱️', 'funeral urn', 'dead'],
  ['🏺', 'amphora', 'vase'],
  ['🔮', 'crystal ball', 'future', 'magic'],
  ['📿', 'prayer beads', 'pray'],
  ['🧿', 'nazar amulet', 'evil eye'],
  ['💈', 'barber pole', 'hair'],
  ['⚗️', 'alembic', 'science'],
  ['🔭', 'telescope', 'science', 'space'],
  ['🔬', 'microscope', 'science'],
  ['🩹', 'adhesive bandage', 'bandage', 'hurt'],
  ['🩺', 'stethoscope', 'doctor'],
  ['💊', 'pill', 'medicine', 'drug'],
  ['💉', 'syringe', 'medicine', 'shot'],
  ['🩸', 'drop of blood', 'blood'],
  ['🧬', 'dna', 'science'],
  ['🦠', 'microbe', 'virus', 'germ'],
  ['🧪', 'test tube', 'science'],
  ['🌡', 'thermometer', 'temperature'],
  ['🧹', 'broom', 'clean'],
  ['🧺', 'basket', 'laundry'],
  ['🧻', 'roll of paper', 'toilet'],
  ['🚽', 'toilet', 'bathroom'],
  ['🚰', 'potable water', 'water'],
  ['🚿', 'shower', 'bath'],
  ['🛁', 'bathtub', 'bath'],
  ['🧼', 'soap', 'clean'],
  ['🪥', 'toothbrush', 'teeth'],
  ['🪒', 'razor', 'shave'],
  ['🧽', 'sponge', 'clean'],
  ['🧴', 'lotion bottle', 'lotion'],
  ['🛎', 'bellhop bell', 'hotel'],
  ['🔑', 'key', 'lock'],
  ['🗝', 'old key', 'key'],
  ['🚪', 'door', 'exit'],
  ['🪑', 'chair', 'sit'],
  ['🛋', 'couch and lamp', 'sofa'],
  ['🛏', 'bed', 'sleep'],
  ['🧸', 'teddy bear', 'toy'],
  ['🖼', 'framed picture', 'art'],
  ['🪞', 'mirror', 'reflect'],
  ['🪟', 'window', 'view'],
  ['🛍', 'shopping bags', 'shop'],
  ['🛒', 'shopping cart', 'shop'],
  ['🎁', 'wrapped gift', 'present', 'gift', 'birthday'],
  ['🎈', 'balloon', 'party'],
  ['🎏', 'carp streamer', 'japan'],
  ['🎀', 'ribbon', 'bow'],
  ['🪄', 'magic wand', 'magic'],
  ['🎊', 'confetti ball', 'party', 'celebrate'],
  ['🎉', 'party popper', 'party', 'celebrate', 'congrats'],
  ['✉️', 'envelope', 'mail', 'email'],
  ['📧', 'e-mail', 'email', 'mail'],
  ['💌', 'love letter', 'love', 'mail'],
  ['📥', 'inbox tray', 'inbox'],
  ['📤', 'outbox tray', 'outbox'],
  ['📦', 'package', 'box', 'parcel'],
  ['📫', 'closed mailbox with raised flag', 'mail'],
  ['📮', 'postbox', 'mail'],
  ['📜', 'scroll', 'document'],
  ['📃', 'page with curl', 'document'],
  ['📄', 'page facing up', 'document'],
  ['📑', 'bookmark tabs', 'bookmark'],
  ['🧾', 'receipt', 'bill'],
  ['📊', 'bar chart', 'chart', 'stats'],
  ['📈', 'chart increasing', 'growth', 'chart'],
  ['📉', 'chart decreasing', 'chart'],
  ['🗒', 'spiral notepad', 'notes'],
  ['🗓', 'spiral calendar', 'calendar'],
  ['📆', 'tear-off calendar', 'calendar'],
  ['📅', 'calendar', 'date'],
  ['🗑', 'wastebasket', 'trash', 'delete'],
  ['📇', 'card index', 'cards'],
  ['📋', 'clipboard', 'copy'],
  ['📁', 'file folder', 'folder'],
  ['📂', 'open file folder', 'folder'],
  ['🗂', 'card index dividers', 'files'],
  ['📰', 'newspaper', 'news'],
  ['📓', 'notebook', 'notes'],
  ['📔', 'notebook with decorative cover', 'notes'],
  ['📒', 'ledger', 'notes'],
  ['📕', 'closed book', 'book'],
  ['📗', 'green book', 'book'],
  ['📘', 'blue book', 'book'],
  ['📙', 'orange book', 'book'],
  ['📚', 'books', 'library', 'study', 'university'],
  ['📖', 'open book', 'read', 'study'],
  ['🔖', 'bookmark', 'mark'],
  ['📎', 'paperclip', 'attach'],
  ['🖇', 'linked paperclips', 'attach'],
  ['📐', 'triangular ruler', 'math'],
  ['📏', 'straight ruler', 'measure'],
  ['📌', 'pushpin', 'pin'],
  ['📍', 'round pushpin', 'location', 'pin'],
  ['✂️', 'scissors', 'cut'],
  ['🖊', 'pen', 'write'],
  ['🖋', 'fountain pen', 'write'],
  ['✒️', 'black nib', 'write'],
  ['🖌', 'paintbrush', 'art'],
  ['🖍', 'crayon', 'draw'],
  ['📝', 'memo', 'note', 'write'],
  ['✏️', 'pencil', 'write'],
  ['🔍', 'magnifying glass tilted left', 'search', 'find'],
  ['🔎', 'magnifying glass tilted right', 'search'],
  ['🔏', 'locked with pen', 'lock'],
  ['🔐', 'locked with key', 'lock', 'secure'],
  ['🔒', 'locked', 'lock', 'secure'],
  ['🔓', 'unlocked', 'unlock'],
];

const SYMBOLS: Row[] = [
  ['❤️', 'red heart', 'heart', 'love'],
  ['🧡', 'orange heart', 'heart', 'love'],
  ['💛', 'yellow heart', 'heart', 'love'],
  ['💚', 'green heart', 'heart', 'love'],
  ['💙', 'blue heart', 'heart', 'love'],
  ['💜', 'purple heart', 'heart', 'love'],
  ['🖤', 'black heart', 'heart', 'love'],
  ['🤍', 'white heart', 'heart', 'love'],
  ['🤎', 'brown heart', 'heart', 'love'],
  ['💔', 'broken heart', 'heart', 'breakup', 'sad'],
  ['❣️', 'heart exclamation', 'heart', 'love'],
  ['💕', 'two hearts', 'heart', 'love'],
  ['💞', 'revolving hearts', 'heart', 'love'],
  ['💓', 'beating heart', 'heart', 'love'],
  ['💗', 'growing heart', 'heart', 'love'],
  ['💖', 'sparkling heart', 'heart', 'love', 'sparkle'],
  ['💘', 'heart with arrow', 'heart', 'love', 'cupid'],
  ['💝', 'heart with ribbon', 'heart', 'gift', 'love'],
  ['💟', 'heart decoration', 'heart'],
  ['☮️', 'peace symbol', 'peace'],
  ['✝️', 'latin cross', 'christian', 'religion'],
  ['☪️', 'star and crescent', 'islam', 'religion'],
  ['🕉', 'om', 'hindu', 'religion'],
  ['☸️', 'wheel of dharma', 'buddhist'],
  ['✡️', 'star of David', 'jewish'],
  ['🔯', 'dotted six-pointed star', 'star'],
  ['☯️', 'yin yang', 'balance'],
  ['⚛️', 'atom symbol', 'science'],
  ['☢️', 'radioactive', 'danger'],
  ['☣️', 'biohazard', 'danger'],
  ['💯', 'hundred points', '100', 'perfect', 'score'],
  ['💢', 'anger symbol', 'angry'],
  ['💥', 'collision', 'boom', 'explode'],
  ['💫', 'dizzy', 'star'],
  ['💦', 'sweat droplets', 'water', 'sweat'],
  ['💨', 'dashing away', 'fast', 'wind'],
  ['🕳', 'hole', 'empty'],
  ['💬', 'speech balloon', 'chat', 'message', 'comment'],
  ['💭', 'thought balloon', 'think'],
  ['💤', 'zzz', 'sleep', 'tired'],
  ['💮', 'white flower', 'flower'],
  ['♨️', 'hot springs', 'onsen'],
  ['💈', 'barber pole', 'barber'],
  ['🛑', 'stop sign', 'stop'],
  ['⛔', 'no entry', 'stop', 'forbidden'],
  ['📛', 'name badge', 'badge'],
  ['🚫', 'prohibited', 'ban', 'no'],
  ['❌', 'cross mark', 'x', 'no', 'wrong'],
  ['⭕', 'hollow red circle', 'o', 'correct'],
  ['✅', 'check mark button', 'check', 'yes', 'done'],
  ['✔️', 'check mark', 'check', 'yes'],
  ['☑️', 'check box with check', 'check'],
  ['➕', 'plus', 'add', 'plus'],
  ['➖', 'minus', 'subtract'],
  ['➗', 'divide', 'division'],
  ['✖️', 'multiply', 'times', 'x'],
  ['♾️', 'infinity', 'forever'],
  ['‼️', 'double exclamation mark', 'exclamation'],
  ['⁉️', 'exclamation question mark', 'surprise'],
  ['❓', 'red question mark', 'question', 'help', '?'],
  ['❔', 'white question mark', 'question'],
  ['❗', 'red exclamation mark', 'exclamation', '!'],
  ['❕', 'white exclamation mark', 'exclamation'],
  ['〰️', 'wavy dash', 'wave'],
  ['💱', 'currency exchange', 'money'],
  ['💲', 'heavy dollar sign', 'money', 'dollar'],
  ['⚕️', 'medical symbol', 'health'],
  ['♻️', 'recycling symbol', 'recycle'],
  ['⚜️', 'fleur-de-lis', 'deco'],
  ['🔱', 'trident emblem', 'trident'],
  ['📛', 'name badge', 'name'],
  ['🔰', 'Japanese symbol for beginner', 'beginner'],
  ['⭕', 'hollow red circle', 'circle'],
  ['✅', 'check mark button', 'ok'],
  ['💠', 'diamond with a dot', 'diamond'],
  ['🔷', 'large blue diamond', 'diamond'],
  ['🔶', 'large orange diamond', 'diamond'],
  ['🔹', 'small blue diamond', 'diamond'],
  ['🔸', 'small orange diamond', 'diamond'],
  ['🔺', 'red triangle pointed up', 'triangle'],
  ['🔻', 'red triangle pointed down', 'triangle'],
  ['🔘', 'radio button', 'button'],
  ['🔴', 'red circle', 'red', 'circle'],
  ['🟠', 'orange circle', 'orange'],
  ['🟡', 'yellow circle', 'yellow'],
  ['🟢', 'green circle', 'green'],
  ['🔵', 'blue circle', 'blue'],
  ['🟣', 'purple circle', 'purple'],
  ['⚫', 'black circle', 'black'],
  ['⚪', 'white circle', 'white'],
  ['🟤', 'brown circle', 'brown'],
  ['🔈', 'speaker low volume', 'sound'],
  ['🔇', 'muted speaker', 'mute'],
  ['🔉', 'speaker medium volume', 'sound'],
  ['🔊', 'speaker high volume', 'sound', 'loud'],
  ['🔔', 'bell', 'notification', 'alert'],
  ['🔕', 'bell with slash', 'mute', 'silent'],
  ['📣', 'megaphone', 'announce'],
  ['📢', 'loudspeaker', 'announce'],
  ['👁‍🗨', 'eye in speech bubble', 'witness'],
  ['♠️', 'spade suit', 'cards'],
  ['♥️', 'heart suit', 'cards', 'heart'],
  ['♦️', 'diamond suit', 'cards'],
  ['♣️', 'club suit', 'cards'],
  ['🃏', 'joker', 'cards'],
  ['🎵', 'musical note', 'music'],
  ['🎶', 'musical notes', 'music'],
  ['♈', 'Aries', 'zodiac'],
  ['♉', 'Taurus', 'zodiac'],
  ['♊', 'Gemini', 'zodiac'],
  ['♋', 'Cancer', 'zodiac'],
  ['♌', 'Leo', 'zodiac'],
  ['♍', 'Virgo', 'zodiac'],
  ['♎', 'Libra', 'zodiac'],
  ['♏', 'Scorpio', 'zodiac'],
  ['♐', 'Sagittarius', 'zodiac'],
  ['♑', 'Capricorn', 'zodiac'],
  ['♒', 'Aquarius', 'zodiac'],
  ['♓', 'Pisces', 'zodiac'],
];

const FLAGS: Row[] = [
  ['🏁', 'chequered flag', 'race', 'finish'],
  ['🚩', 'triangular flag', 'flag'],
  ['🎌', 'crossed flags', 'japan'],
  ['🏴', 'black flag', 'flag'],
  ['🏳️', 'white flag', 'flag', 'surrender'],
  ['🏳️‍🌈', 'rainbow flag', 'pride', 'lgbt'],
  ['🏳️‍⚧️', 'transgender flag', 'trans', 'pride'],
  ['🏴‍☠️', 'pirate flag', 'pirate'],
  ['🇹🇿', 'flag Tanzania', 'tanzania', 'tz', 'flag'],
  ['🇰🇪', 'flag Kenya', 'kenya', 'flag'],
  ['🇺🇬', 'flag Uganda', 'uganda', 'flag'],
  ['🇷🇼', 'flag Rwanda', 'rwanda', 'flag'],
  ['🇿🇦', 'flag South Africa', 'south africa', 'flag'],
  ['🇳🇬', 'flag Nigeria', 'nigeria', 'flag'],
  ['🇬🇭', 'flag Ghana', 'ghana', 'flag'],
  ['🇪🇹', 'flag Ethiopia', 'ethiopia', 'flag'],
  ['🇪🇬', 'flag Egypt', 'egypt', 'flag'],
  ['🇲🇦', 'flag Morocco', 'morocco', 'flag'],
  ['🇺🇸', 'flag United States', 'usa', 'america', 'flag'],
  ['🇬🇧', 'flag United Kingdom', 'uk', 'britain', 'flag'],
  ['🇫🇷', 'flag France', 'france', 'flag'],
  ['🇩🇪', 'flag Germany', 'germany', 'flag'],
  ['🇮🇹', 'flag Italy', 'italy', 'flag'],
  ['🇪🇸', 'flag Spain', 'spain', 'flag'],
  ['🇵🇹', 'flag Portugal', 'portugal', 'flag'],
  ['🇧🇷', 'flag Brazil', 'brazil', 'flag'],
  ['🇮🇳', 'flag India', 'india', 'flag'],
  ['🇨🇳', 'flag China', 'china', 'flag'],
  ['🇯🇵', 'flag Japan', 'japan', 'flag'],
  ['🇰🇷', 'flag South Korea', 'korea', 'flag'],
  ['🇦🇺', 'flag Australia', 'australia', 'flag'],
  ['🇨🇦', 'flag Canada', 'canada', 'flag'],
  ['🇲🇽', 'flag Mexico', 'mexico', 'flag'],
  ['🇦🇪', 'flag United Arab Emirates', 'uae', 'flag'],
  ['🇸🇦', 'flag Saudi Arabia', 'saudi', 'flag'],
];

export const AO_EMOJI_CATEGORIES: AoEmojiCategory[] = [
  { id: 'recent', label: 'Recent', icon: '🕒', dynamic: true },
  { id: 'smileys', label: 'Smileys', icon: '😀' },
  { id: 'people', label: 'People', icon: '👋' },
  { id: 'animals', label: 'Animals', icon: '🐶' },
  { id: 'food', label: 'Food', icon: '🍔' },
  { id: 'travel', label: 'Travel', icon: '🌍' },
  { id: 'activities', label: 'Activities', icon: '⚽' },
  { id: 'objects', label: 'Objects', icon: '💡' },
  { id: 'symbols', label: 'Symbols', icon: '🔣' },
  { id: 'flags', label: 'Flags', icon: '🏳️' },
  { id: 'ao_premium', label: 'AO Premium', icon: '✨' },
];

const UNICODE_BY_CATEGORY: Record<string, AoEmojiItem[]> = {
  smileys: rowsToItems('smileys', SMILEYS),
  people: rowsToItems('people', PEOPLE),
  animals: rowsToItems('animals', ANIMALS),
  food: rowsToItems('food', FOOD),
  travel: rowsToItems('travel', TRAVEL),
  activities: rowsToItems('activities', ACTIVITIES),
  objects: rowsToItems('objects', OBJECTS),
  symbols: rowsToItems('symbols', SYMBOLS),
  flags: rowsToItems('flags', FLAGS),
};

let _allUnicode: AoEmojiItem[] | null = null;
let _byId: Map<string, AoEmojiItem> | null = null;

export function getUnicodeEmojis(): AoEmojiItem[] {
  if (!_allUnicode) {
    _allUnicode = Object.values(UNICODE_BY_CATEGORY).flat();
  }
  return _allUnicode;
}

export function getUnicodeByCategory(categoryId: string): AoEmojiItem[] {
  return UNICODE_BY_CATEGORY[categoryId] ?? [];
}

export function getEmojiById(id: string): AoEmojiItem | undefined {
  if (!_byId) {
    _byId = new Map(getUnicodeEmojis().map((e) => [e.id, e]));
  }
  return _byId.get(id);
}
