export const en = {
  app: { name: 'AO Chats', tagline: 'Connect. Chat. Belong.' },
  auth: {
    login: 'Login',
    register: 'Create Account',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    firstName: 'First Name',
    lastName: 'Last Name',
    username: 'Username',
    university: 'University',
    course: 'Course (Optional)',
    welcome: 'Welcome to AO Chats',
    welcomeSubtitle: 'Your university community awaits',
    verifyEmail: 'Verify Email',
    verifySubtitle: 'Enter the 6-digit code sent to your email',
    codeSentTo: 'Code sent to',
    codeExpiresIn: 'Code expires in',
    codeExpired: 'Code expired. Tap Resend for a new code.',
    resendCode: 'Resend Code',
    resendIn: 'Resend in',
    verifyNow: 'Verify Email',
    verifyLoginPrompt: 'Your account exists but email is not verified yet. Verify now to continue.',
    chooseAvatar: 'Choose Your Avatar',
    next: 'Next',
    back: 'Back',
    finish: 'Finish',
    step: 'Step',
    of: 'of',
  },
  home: {
    title: 'Chats',
    search: 'Search conversations',
    noChats: 'No conversations yet',
    startChat: 'Start a conversation with a friend',
    pinned: 'Pinned',
  },
  chat: {
    typeMessage: 'Type a message...',
    online: 'Online',
    offline: 'Offline',
    typing: 'typing...',
    delivered: 'Delivered',
    read: 'Read',
    reply: 'Reply',
    react: 'React',
    copy: 'Copy',
    forward: 'Forward',
    delete: 'Delete',
    deleteForMe: 'Delete for me',
    deleteForEveryone: 'Delete for everyone',
    pin: 'Pin',
    unpin: 'Unpin',
    pinned: 'Pinned Messages',
    searchMessages: 'Search messages',
    noMessages: 'No messages yet',
    sayHello: 'Say hello!',
  },
  friends: {
    title: 'Friends',
    search: 'Search users',
    addFriend: 'Add Friend',
    pending: 'Pending Requests',
    sent: 'Sent Requests',
    accept: 'Accept',
    reject: 'Reject',
    remove: 'Remove Friend',
    block: 'Block',
    unblock: 'Unblock',
    noFriends: 'No friends yet',
    findFriends: 'Find friends on campus',
  },
  profile: {
    title: 'Profile',
    edit: 'Edit Profile',
    bio: 'Bio',
    status: 'Status',
    save: 'Save',
    cancel: 'Cancel',
    personalInfo: 'Personal Information',
    education: 'Education',
    privateInfo: 'Private Information',
    accountInfo: 'Account',
    mobileNumber: 'Mobile Number',
    memberSince: 'Member Since',
    onlineStatus: 'Status',
    verified: 'Verified',
    privateOnly: 'Visible only to you',
    noChanges: 'No changes to save',
    saved: 'Profile updated successfully',
    mobileHint: 'International format e.g. +254712345678',
  },
  settings: {
    title: 'Settings',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    english: 'English',
    swahili: 'Swahili',
    fontSize: 'Font Size',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    privacy: 'Privacy',
    blockedUsers: 'Blocked Users',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    notifications: 'Notifications',
    support: 'Support',
    aoManager: 'Chat with AO Manager',
    aoManagerDesc: 'Official AO Chats Support',
    aoManagerUnavailable: 'AO Manager is temporarily unavailable. Please try again.',
  },
  common: {
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Retry',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    search: 'Search',
    noResults: 'No results found',
  },
  tabs: { chats: 'Chats', friends: 'Friends', profile: 'Profile', settings: 'Settings' },
};

export const sw: typeof en = {
  app: { name: 'AO Chats', tagline: 'Ungana. Ongea. Jumuika.' },
  auth: {
    login: 'Ingia',
    register: 'Unda Akaunti',
    email: 'Barua pepe',
    password: 'Nywila',
    confirmPassword: 'Thibitisha Nywila',
    rememberMe: 'Nikumbuke',
    forgotPassword: 'Umesahau nywila?',
    noAccount: 'Huna akaunti?',
    hasAccount: 'Tayari una akaunti?',
    firstName: 'Jina la Kwanza',
    lastName: 'Jina la Mwisho',
    username: 'Jina la mtumiaji',
    university: 'Chuo Kikuu',
    course: 'Kozi (Hiari)',
    welcome: 'Karibu AO Chats',
    welcomeSubtitle: 'Jumuiya yako ya chuo inakusubiri',
    verifyEmail: 'Thibitisha Barua pepe',
    verifySubtitle: 'Weka msimbo wa tarakimu 6 uliotumwa kwenye barua pepe yako',
    codeSentTo: 'Msimbo umetumwa kwa',
    codeExpiresIn: 'Msimbo unaisha baada ya',
    codeExpired: 'Msimbo umeisha. Bonyeza Tuma tena kwa msimbo mpya.',
    resendCode: 'Tuma tena Msimbo',
    resendIn: 'Tuma tena baada ya',
    verifyNow: 'Thibitisha Barua pepe',
    verifyLoginPrompt: 'Akaunti yako ipo lakini barua pepe haijathibitishwa. Thibitisha sasa ili uendelee.',
    chooseAvatar: 'Chagua Picha Yako',
    next: 'Ifuatayo',
    back: 'Rudi',
    finish: 'Maliza',
    step: 'Hatua',
    of: 'ya',
  },
  home: {
    title: 'Mazungumzo',
    search: 'Tafuta mazungumzo',
    noChats: 'Hakuna mazungumzo bado',
    startChat: 'Anza mazungumzo na rafiki',
    pinned: 'Imebandikwa',
  },
  chat: {
    typeMessage: 'Andika ujumbe...',
    online: 'Mtandaoni',
    offline: 'Nje ya mtandao',
    typing: 'anaandika...',
    delivered: 'Imewasilishwa',
    read: 'Imesomwa',
    reply: 'Jibu',
    react: 'Onyesha hisia',
    copy: 'Nakili',
    forward: 'Sambaza',
    delete: 'Futa',
    deleteForMe: 'Futa kwangu',
    deleteForEveryone: 'Futa kwa wote',
    pin: 'Bandika',
    unpin: 'Ondoa bandiko',
    pinned: 'Ujumbe Uliobandikwa',
    searchMessages: 'Tafuta ujumbe',
    noMessages: 'Hakuna ujumbe bado',
    sayHello: 'Sema hujambo!',
  },
  friends: {
    title: 'Marafiki',
    search: 'Tafuta watumiaji',
    addFriend: 'Ongeza Rafiki',
    pending: 'Maombi Yanayosubiri',
    sent: 'Maombi Yaliyotumwa',
    accept: 'Kubali',
    reject: 'Kataa',
    remove: 'Ondoa Rafiki',
    block: 'Zuia',
    unblock: 'Ondoa Zuio',
    noFriends: 'Hakuna marafiki bado',
    findFriends: 'Tafuta marafiki chuoni',
  },
  profile: {
    title: 'Wasifu',
    edit: 'Hariri Wasifu',
    bio: 'Wasifu',
    status: 'Hali',
    save: 'Hifadhi',
    cancel: 'Ghairi',
    personalInfo: 'Taarifa Binafsi',
    education: 'Elimu',
    privateInfo: 'Taarifa Faragha',
    accountInfo: 'Akaunti',
    mobileNumber: 'Nambari ya Simu',
    memberSince: 'Mwanachama Tangu',
    onlineStatus: 'Hali',
    verified: 'Imethibitishwa',
    privateOnly: 'Inaonekana kwako tu',
    noChanges: 'Hakuna mabadiliko ya kuhifadhi',
    saved: 'Wasifu umesasishwa',
    mobileHint: 'Muundo wa kimataifa mfano +254712345678',
  },
  settings: {
    title: 'Mipangilio',
    theme: 'Mandhari',
    light: 'Nuru',
    dark: 'Giza',
    language: 'Lugha',
    english: 'Kiingereza',
    swahili: 'Kiswahili',
    fontSize: 'Ukubwa wa Herufi',
    small: 'Ndogo',
    medium: 'Wastani',
    large: 'Kubwa',
    privacy: 'Faragha',
    blockedUsers: 'Watumiaji Waliozuiliwa',
    logout: 'Toka',
    logoutConfirm: 'Una uhakika unataka kutoka?',
    notifications: 'Arifa',
    support: 'Msaada',
    aoManager: 'Ongea na AO Manager',
    aoManagerDesc: 'Msaada Rasmi wa AO Chats',
    aoManagerUnavailable: 'AO Manager haipatikani kwa sasa. Jaribu tena.',
  },
  common: {
    loading: 'Inapakia...',
    error: 'Kuna tatizo limetokea',
    retry: 'Jaribu tena',
    cancel: 'Ghairi',
    confirm: 'Thibitisha',
    save: 'Hifadhi',
    delete: 'Futa',
    search: 'Tafuta',
    noResults: 'Hakuna matokeo',
  },
  tabs: { chats: 'Mazungumzo', friends: 'Marafiki', profile: 'Wasifu', settings: 'Mipangilio' },
};

export type Translations = typeof en;
