export const en = {
  app: { name: 'AO Chats', tagline: 'Connect. Chat. Belong.' },
  auth: {
    login: 'Login',
    register: 'Create Account',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    firstName: 'First Name',
    lastName: 'Last Name',
    username: 'Username',
    university: 'University',
    course: 'Course (Optional)',
    welcome: 'Welcome to AO Chats',
    welcomeSubtitle: 'Your university community awaits',
    verifyEmail: 'Verify Email',
    verifySubtitle: 'Enter the 6-digit code sent to your email',
    codeSentTo: 'Code sent to',
    codeExpiresIn: 'Code expires in',
    codeExpired: 'Code expired. Tap Resend for a new code.',
    resendCode: 'Resend Code',
    resendIn: 'Resend in',
    verifyNow: 'Verify Email',
    verifyLoginPrompt: 'Your account exists but email is not verified yet. Verify now to continue.',
    noAccountForEmail: 'No account available for this email. Please create one.',
    incorrectPassword: 'Incorrect password. Please try again.',
    createAccount: 'Create account',
    chooseAvatar: 'Choose Your Avatar',
    next: 'Next',
    back: 'Back',
    finish: 'Finish',
    step: 'Step',
    of: 'of',
    resetPasswordTitle: 'Reset Password',
    resetPasswordSubtitle: 'Enter your email to receive a verification code',
    sendResetCode: 'Send Reset Code',
    resetCode: 'Verification Code',
    newPassword: 'New Password',
    resetSuccess: 'Password updated',
    resetSuccessMessage: 'You can now sign in with your new password.',
    backToLogin: 'Back to Login',
    invalidEmail: 'Please enter a valid email address.',
    passwordMismatch: 'Passwords do not match.',
    resetCodeSent: 'If the email exists, a reset code has been sent.',
    resetCooldown: 'Resend available in',
    resetExpired: 'This code has expired. Please request a new one.',
    invalidResetCode: 'The verification code is incorrect.',
    resetAttempts: 'Too many attempts. Please request a new code.',
    emailSendFailed: "We couldn't send the verification code. Please try again.",
  },
  home: {
    title: 'Chats',
    search: 'Search conversations',
    noChats: 'No conversations yet',
    startChat: 'Start a conversation with a friend',
    pinned: 'Pinned',
    draft: 'Draft',
    sending: 'Sending…',
    sendFailed: 'Not sent',
    deleteChat: 'Delete Chat',
    deleteChatTitle: 'Delete this chat?',
    deleteChatMessage: 'This chat and its history will be removed from your list. The other person will still have it.',
    deleteSelectedTitle: 'Delete selected chats?',
    deleteSelectedMessage: 'Selected chats and their history will be removed from your list. Other users are not affected.',
    removeChat: 'Remove',
    removeChatTitle: 'Remove from chat list?',
    removeChatMessage: 'This chat will disappear from your list. Message history is kept and the chat can return if someone sends a new message.',
    removeSelectedTitle: 'Remove selected chats?',
    removeSelectedMessage: 'Selected chats will disappear from your list. Message history is kept.',
    blockSelectedTitle: 'Block selected users?',
    blockSelectedMessage: 'You will no longer be able to communicate with these users while the block is active.',
    conversationsRemoved: 'Conversation removed',
    conversationsRemovedMany: 'conversations removed',
    conversationsDeleted: 'Conversation deleted',
    conversationsDeletedMany: 'conversations deleted',
    usersBlocked: 'User blocked',
    usersBlockedMany: 'users blocked',
    removeFailed: 'Could not remove chat. Please try again.',
    blockFailed: 'Could not block user. Please try again.',
    deleteAll: 'Delete All Chats',
    deleteAllTitle: 'Delete all chats from your chat list?',
    deleteAllMessage: 'This only removes chats from your list. Other users are not affected.',
    chatOptions: 'Chat options',
    deleteFailed: 'Could not delete chat. Please try again.',
    loadChatsFailed: 'AO Chats is temporarily unable to load your chats. Please try again.',
    sessionExpired: 'Your session has expired. Please log in again.',
    syncing: 'Syncing…',
  },
  chat: {
    typeMessage: 'Type a message...',
    send: 'Send',
    online: 'Online',
    offline: 'Offline',
    typing: 'typing...',
    delivered: 'Delivered',
    read: 'Read',
    reply: 'Reply',
    react: 'React',
    copy: 'Copy',
    forward: 'Forward',
    delete: 'Delete',
    deleteForMe: 'Delete for me',
    deleteForEveryone: 'Delete for everyone',
    clearChat: 'Clear chat',
    clearChatConfirm: 'Delete all messages in this chat for you? This cannot be undone.',
    clearChatDone: 'Chat cleared',
    chatSettings: 'Chat settings',
    edit: 'Edit',
    editMessage: 'Edit message',
    edited: 'edited',
    saveEdit: 'Save',
    cancelEdit: 'Cancel',
    pin: 'Pin',
    unpin: 'Unpin',
    pinned: 'Pinned Messages',
    star: 'Star',
    unstar: 'Unstar',
    info: 'Info',
    you: 'You',
    selected: 'selected',
    sendFailed: 'Failed to send message. Tap to retry.',
    messageInfo: 'Message Info',
    sentAt: 'Sent',
    deliveredAt: 'Delivered',
    readAt: 'Read',
    sender: 'Sender',
    messageId: 'Message ID',
    forwarded: 'Message forwarded',
    searchMessages: 'Search messages',
    noMessages: 'No messages yet',
    sayHello: 'Say hello!',
    unreadMessages: 'Unread Messages',
    starredMessages: 'Starred Messages',
    searchStarred: 'Search starred messages',
    noStarred: 'No starred messages yet',
    deletedMessage: 'This message was deleted',
    searchEmoji: 'Search emoji',
    noEmojiFound: 'No emoji found',
    recentEmojis: 'Recent',
    aoPremium: 'AO Premium',
    pinHeader: 'Pinned',
    seeMore: 'See more',
    seeLess: 'See less',
    scrollDown: 'Scroll down',
    noPinned: 'No pinned messages',
    messageUnavailable: 'This message is no longer available.',
    unpinFailed: 'Could not unpin message. Please try again.',
    deleteMessageFailed: 'Could not delete message. Please try again.',
    attach: 'Attach',
    attachmentTitle: 'Share',
    gallery: 'Gallery',
    document: 'Document',
    linkOther: 'Link',
    recentMedia: 'Recent',
    addCaption: 'Add a message...',
    uploading: 'Uploading…',
    uploadFailed: 'Upload failed. Try again.',
    download: 'Download',
    downloading: 'Downloading',
    downloadFailed: 'Download failed. Try again.',
    openFile: 'Open',
    retry: 'Retry',
    openLink: 'Open',
    openEmail: 'Open email',
    openLocation: 'Open location',
    call: 'Call',
    linkCopied: 'Link copied',
    emailCopied: 'Email copied',
    phoneCopied: 'Phone number copied',
    locationCopied: 'Location copied',
    fileTooLarge: 'This file is too large to upload.',
    unsupportedType: "This file type isn't supported.",
  },
  media: {
    title: 'Media',
    loading: 'Loading media…',
    unavailable: 'Media unavailable. It may have been deleted or you may not have permission to view it.',
    retry: 'Retry',
    actions: 'Media actions',
    saveToDevice: 'Save to device',
    share: 'Share',
    copyLink: 'Copy link',
    linkCopied: 'Link copied',
    saved: 'Saved to device',
    saveFailed: 'Could not save media.',
    shareFailed: 'Could not share media.',
    openingDocument: 'Opening document…',
    openWith: 'Open',
    sender: 'Sender',
    clearCache: 'Clear media cache',
    clearCacheConfirm:
      'Cached photos, videos, and documents will be removed from this device. Chat messages stay on the server. You may need to download media again to view offline.',
    clearCacheDone: 'Media cache cleared',
  },
  friends: {
    title: 'Friends',
    search: 'Search users',
    addFriend: 'Add Friend',
    pending: 'Pending Requests',
    sent: 'Sent Requests',
    accept: 'Accept',
    reject: 'Reject',
    remove: 'Remove Friend',
    block: 'Block',
    unblock: 'Unblock',
    noFriends: 'No friends yet',
    findFriends: 'Find friends on campus',
    pendingLabel: 'Pending',
    startChat: 'Start Chat',
    chat: 'Chat',
    requestSent: 'Friend request sent',
    pendingIncoming: 'Pending — accept as friend',
    pendingOutgoing: 'Sent Requests',
    yourFriends: 'Your friends',
    wantsToBeFriend: 'Wants to be your friend',
    waitingForAccept: 'Waiting for them to accept',
    waitingForResponse: 'Waiting for response',
    noPendingRequests: 'No pending friend requests',
    searchHint: 'Type at least 2 characters to search',
    cancelRequest: 'Cancel',
  },
  notifications: {
    title: 'Notifications',
    unread: 'unread',
    markAllRead: 'Mark all read',
    empty: 'No notifications yet',
    pullUp: 'Swipe up for full screen',
    pullDown: 'Swipe down to minimize',
    friendRequest: 'Friend request',
    friendAccepted: 'Friend accepted',
    newMessage: 'New message',
  },
  profile: {
    title: 'Profile',
    edit: 'Edit Profile',
    bio: 'Bio',
    status: 'Status',
    save: 'Save',
    cancel: 'Cancel',
    personalInfo: 'Personal Information',
    education: 'Education',
    viewAllUniversities: 'Browse all universities',
    privateInfo: 'Private Information',
    accountInfo: 'Account',
    mobileNumber: 'Mobile Number',
    memberSince: 'Member Since',
    onlineStatus: 'Status',
    verified: 'Verified',
    privateOnly: 'Visible only to you',
    noChanges: 'No changes to save',
    saved: 'Profile updated successfully',
    mobileHint: 'International format e.g. +254712345678',
    friendsCount: 'Friends',
    pendingRequests: 'Pending Requests',
    sentRequests: 'Sent Requests',
    changePhoto: 'Change Profile Picture',
    removePhoto: 'Remove Profile Photo',
    removePhotoConfirm: 'Remove your custom profile photo and choose an AO Chats avatar?',
    photoPreview: 'Preview',
    photoSaved: 'Profile photo saved',
    photoRemoved: 'Photo removed — choose an avatar',
    photoFailed: 'Could not update profile picture',
    photoSaveFailed: 'Profile photo could not be saved. Try again.',
    useAoAvatar: 'AO Avatars',
    chooseAvatar: 'Choose your profile avatar',
    photoMenuTitle: 'Profile Photo',
    viewProfilePhoto: 'View Profile',
  },
  friendInfo: {
    title: 'Friend Info',
    message: 'Message',
    conversation: 'Conversation',
    sharedMedia: 'Shared Media',
    photos: 'Photos',
    videos: 'Videos',
    documents: 'Documents',
    links: 'Links',
    privacy: 'Privacy',
    block: 'Block',
    blockConfirm: 'Block this user? You will no longer be able to message each other.',
    clearChat: 'Clear Conversation',
    clearChatConfirm: 'Delete all messages in this chat for you? This cannot be undone.',
    deleteChat: 'Delete Conversation',
    deleteChatConfirm: 'Remove this conversation from your list?',
    offlineCached: 'Showing cached profile',
    emptyMedia: 'No shared media yet',
    sharedOn: 'Shared',
    openLink: 'Open',
    copyLink: 'Copy',
    networkRequired: 'Connect to the internet to load this media.',
  },
  settings: {
    title: 'Settings',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    english: 'English',
    swahili: 'Swahili',
    fontSize: 'Font Size',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    privacy: 'Privacy',
    blockedUsers: 'Blocked Users',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    notifications: 'Notifications',
    support: 'Support',
    aoManager: 'Chat with AO Manager',
    aoManagerDesc: 'Official AO Chats Support',
    aoManagerUnavailable: 'AO Manager is temporarily unavailable. Please try again.',
    universitiesDirectory: 'Universities in Tanzania',
    viewAllUniversities: 'Browse all universities',
    searchUniversities: 'Search by name, abbreviation, or location',
    universityAbbreviation: 'Abbreviation',
    universityLocation: 'Location',
    noUniversitiesMatch: 'No universities match your search',
    sounds: 'Sounds & Vibration',
    chatSound: 'Chat Sound',
    chatVibration: 'Chat Vibration',
    notificationSound: 'Notification Sound',
    notificationVibration: 'Notification Vibration',
  },
  common: {
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Retry',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    search: 'Search',
    noResults: 'No results found',
  },
  tabs: { chats: 'Chats', friends: 'Friends', profile: 'Profile', settings: 'Settings' },
};

export const sw: typeof en = {
  app: { name: 'AO Chats', tagline: 'Ungana. Ongea. Jumuika.' },
  auth: {
    login: 'Ingia',
    register: 'Unda Akaunti',
    email: 'Barua pepe',
    password: 'Nywila',
    confirmPassword: 'Thibitisha Nywila',
    rememberMe: 'Nikumbuke',
    forgotPassword: 'Umesahau nywila?',
    noAccount: 'Huna akaunti?',
    hasAccount: 'Tayari una akaunti?',
    firstName: 'Jina la Kwanza',
    lastName: 'Jina la Mwisho',
    username: 'Jina la mtumiaji',
    university: 'Chuo Kikuu',
    course: 'Kozi (Hiari)',
    welcome: 'Karibu AO Chats',
    welcomeSubtitle: 'Jumuiya yako ya chuo inakusubiri',
    verifyEmail: 'Thibitisha Barua pepe',
    verifySubtitle: 'Weka msimbo wa tarakimu 6 uliotumwa kwenye barua pepe yako',
    codeSentTo: 'Msimbo umetumwa kwa',
    codeExpiresIn: 'Msimbo unaisha baada ya',
    codeExpired: 'Msimbo umeisha. Bonyeza Tuma tena kwa msimbo mpya.',
    resendCode: 'Tuma tena Msimbo',
    resendIn: 'Tuma tena baada ya',
    verifyNow: 'Thibitisha Barua pepe',
    verifyLoginPrompt: 'Akaunti yako ipo lakini barua pepe haijathibitishwa. Thibitisha sasa ili uendelee.',
    noAccountForEmail: 'Hakuna akaunti kwa barua pepe hii. Tafadhali unda moja.',
    incorrectPassword: 'Nywila si sahihi. Jaribu tena.',
    createAccount: 'Unda akaunti',
    chooseAvatar: 'Chagua Picha Yako',
    next: 'Ifuatayo',
    back: 'Rudi',
    finish: 'Maliza',
    step: 'Hatua',
    of: 'ya',
    resetPasswordTitle: 'Weka Upya Nywila',
    resetPasswordSubtitle: 'Weka barua pepe yako kupokea msimbo wa uthibitisho',
    sendResetCode: 'Tuma Msimbo wa Kuweka Upya',
    resetCode: 'Msimbo wa Uthibitisho',
    newPassword: 'Nywila Mpya',
    resetSuccess: 'Nywila imesasishwa',
    resetSuccessMessage: 'Sasa unaweza kuingia kwa nywila yako mpya.',
    backToLogin: 'Rudi Kuingia',
    invalidEmail: 'Tafadhali weka barua pepe sahihi.',
    passwordMismatch: 'Nywila hazilingani.',
    resetCodeSent: 'Ikiwa barua pepe ipo, msimbo wa kuweka upya umetumwa.',
    resetCooldown: 'Tuma tena baada ya',
    resetExpired: 'Msimbo huu umeisha. Tafadhali omba msimbo mpya.',
    invalidResetCode: 'Msimbo wa uthibitisho si sahihi.',
    resetAttempts: 'Majaribio mengi sana. Tafadhali omba msimbo mpya.',
    emailSendFailed: 'Hatukuweza kutuma msimbo wa uthibitisho. Jaribu tena.',
  },
  home: {
    title: 'Mazungumzo',
    search: 'Tafuta mazungumzo',
    noChats: 'Hakuna mazungumzo bado',
    startChat: 'Anza mazungumzo na rafiki',
    pinned: 'Imebandikwa',
    draft: 'Rasimu',
    sending: 'Inatumwa…',
    sendFailed: 'Haijatumwa',
    deleteChat: 'Futa Mazungumzo',
    deleteChatTitle: 'Unataka kufuta mazungumzo haya?',
    deleteChatMessage: 'Mazungumzo na historia yake yataondolewa kwenye orodha yako. Mtu mwingine ataendelea kuyaona.',
    deleteSelectedTitle: 'Unataka kufuta mazungumzo yaliyochaguliwa?',
    deleteSelectedMessage: 'Mazungumzo yaliyochaguliwa na historia yake yataondolewa kwenye orodha yako. Watumiaji wengine hawathiriki.',
    removeChat: 'Ondoa',
    removeChatTitle: 'Ondoa kwenye orodha ya mazungumzo?',
    removeChatMessage: 'Mazungumzo yatatoweka kwenye orodha yako. Historia inahifadhiwa na yanaweza kurudi ukitumwa ujumbe mpya.',
    removeSelectedTitle: 'Ondoa mazungumzo yaliyochaguliwa?',
    removeSelectedMessage: 'Mazungumzo yaliyochaguliwa yatatoweka kwenye orodha yako. Historia inahifadhiwa.',
    blockSelectedTitle: 'Zuia watumiaji waliochaguliwa?',
    blockSelectedMessage: 'Hutaweza kuwasiliana na watumiaji hawa wakati zuio likiwa limetumika.',
    conversationsRemoved: 'Mazungumzo yameondolewa',
    conversationsRemovedMany: 'mazungumzo yameondolewa',
    conversationsDeleted: 'Mazungumzo yamefutwa',
    conversationsDeletedMany: 'mazungumzo yamefutwa',
    usersBlocked: 'Mtumiaji amezuiwa',
    usersBlockedMany: 'watumiaji wamezuiwa',
    removeFailed: 'Imeshindwa kuondoa mazungumzo. Jaribu tena.',
    blockFailed: 'Imeshindwa kumzuia mtumiaji. Jaribu tena.',
    deleteAll: 'Futa Mazungumzo Yote',
    deleteAllTitle: 'Unataka kufuta mazungumzo yote kwenye orodha yako?',
    deleteAllMessage: 'Hii inaondoa mazungumzo kwenye orodha yako tu. Watumiaji wengine hawathiriki.',
    chatOptions: 'Chaguo za mazungumzo',
    deleteFailed: 'Imeshindwa kufuta mazungumzo. Jaribu tena.',
    loadChatsFailed: 'Imeshindwa kupakia mazungumzo yako kwa sasa. Jaribu tena.',
    sessionExpired: 'Kipindi chako kimeisha. Tafadhali ingia tena.',
    syncing: 'Inalandanisha…',
  },
  chat: {
    typeMessage: 'Andika ujumbe...',
    send: 'Tuma',
    online: 'Mtandaoni',
    offline: 'Nje ya mtandao',
    typing: 'anaandika...',
    delivered: 'Imewasilishwa',
    read: 'Imesomwa',
    reply: 'Jibu',
    react: 'Onyesha hisia',
    copy: 'Nakili',
    forward: 'Sambaza',
    delete: 'Futa',
    deleteForMe: 'Futa kwangu',
    deleteForEveryone: 'Futa kwa wote',
    clearChat: 'Futa mazungumzo yote',
    clearChatConfirm: 'Unataka kufuta ujumbe wote kwenye chat hii kwako? Huwezi kurudisha.',
    clearChatDone: 'Mazungumzo yamefutwa',
    chatSettings: 'Mipangilio ya mazungumzo',
    edit: 'Hariri',
    editMessage: 'Hariri ujumbe',
    edited: 'imehaririwa',
    saveEdit: 'Hifadhi',
    cancelEdit: 'Ghairi',
    pin: 'Bandika',
    unpin: 'Ondoa bandiko',
    pinned: 'Ujumbe Uliobandikwa',
    star: 'Nyota',
    unstar: 'Ondoa nyota',
    info: 'Taarifa',
    you: 'Wewe',
    selected: 'imechaguliwa',
    sendFailed: 'Imeshindwa kutuma. Bonyeza kujaribu tena.',
    messageInfo: 'Taarifa za Ujumbe',
    sentAt: 'Imetumwa',
    deliveredAt: 'Imewasilishwa',
    readAt: 'Imesomwa',
    sender: 'Mtumaji',
    messageId: 'Kitambulisho cha Ujumbe',
    forwarded: 'Ujumbe umesambazwa',
    searchMessages: 'Tafuta ujumbe',
    noMessages: 'Hakuna ujumbe bado',
    sayHello: 'Sema hujambo!',
    unreadMessages: 'Ujumbe Usiosomwa',
    starredMessages: 'Ujumbe wenye Nyota',
    searchStarred: 'Tafuta ujumbe wenye nyota',
    noStarred: 'Hakuna ujumbe wenye nyota bado',
    deletedMessage: 'Ujumbe huu umefutwa',
    searchEmoji: 'Tafuta emoji',
    noEmojiFound: 'Hakuna emoji iliyopatikana',
    recentEmojis: 'Hivi karibuni',
    aoPremium: 'AO Premium',
    pinHeader: 'Imebandikwa',
    seeMore: 'Ona zaidi',
    seeLess: 'Ona kidogo',
    scrollDown: 'Scroll chini',
    noPinned: 'Hakuna ujumbe uliobandikwa',
    messageUnavailable: 'Ujumbe huu haupatikani tena.',
    unpinFailed: 'Imeshindikana kuondoa bandiko. Jaribu tena.',
    deleteMessageFailed: 'Imeshindikana kufuta ujumbe. Jaribu tena.',
    attach: 'Ambatisha',
    attachmentTitle: 'Shiriki',
    gallery: 'Galeri',
    document: 'Hati',
    linkOther: 'Kiungo',
    recentMedia: 'Hivi karibuni',
    addCaption: 'Ongeza ujumbe...',
    uploading: 'Inapakia…',
    uploadFailed: 'Upakiaji umeshindikana. Jaribu tena.',
    download: 'Pakua',
    downloading: 'Inapakua',
    downloadFailed: 'Upakuaji umeshindikana. Jaribu tena.',
    openFile: 'Fungua',
    retry: 'Jaribu tena',
    openLink: 'Fungua',
    openEmail: 'Fungua barua pepe',
    openLocation: 'Fungua eneo',
    call: 'Piga simu',
    linkCopied: 'Kiungo kimenakiliwa',
    emailCopied: 'Barua pepe imenakiliwa',
    phoneCopied: 'Namba imenakiliwa',
    locationCopied: 'Eneo limenakiliwa',
    fileTooLarge: 'Faili hii ni kubwa sana kupakiwa.',
    unsupportedType: 'Aina hii ya faili haitumiki.',
  },
  media: {
    title: 'Media',
    loading: 'Inapakia media…',
    unavailable:
      'Media haipatikani. Huenda imefutwa au huna ruhusa ya kuiona.',
    retry: 'Jaribu tena',
    actions: 'Vitendo vya media',
    saveToDevice: 'Hifadhi kwenye kifaa',
    share: 'Shiriki',
    copyLink: 'Nakili kiungo',
    linkCopied: 'Kiungo kimenakiliwa',
    saved: 'Imehifadhiwa kwenye kifaa',
    saveFailed: 'Imeshindikana kuhifadhi media.',
    shareFailed: 'Imeshindikana kushiriki media.',
    openingDocument: 'Inafungua hati…',
    openWith: 'Fungua',
    sender: 'Mtumaji',
    clearCache: 'Futa cache ya media',
    clearCacheConfirm:
      'Picha, video na hati zilizohifadhiwa kwenye kifaa hiki zitafutwa. Ujumbe unabaki kwenye seva. Huenda utahitaji kupakua tena ili kuona offline.',
    clearCacheDone: 'Cache ya media imefutwa',
  },
  friends: {
    title: 'Marafiki',
    search: 'Tafuta watumiaji',
    addFriend: 'Ongeza Rafiki',
    pending: 'Maombi Yanayosubiri',
    sent: 'Maombi Yaliyotumwa',
    accept: 'Kubali',
    reject: 'Kataa',
    remove: 'Ondoa Rafiki',
    block: 'Zuia',
    unblock: 'Ondoa Zuio',
    noFriends: 'Hakuna marafiki bado',
    findFriends: 'Tafuta marafiki chuoni',
    pendingLabel: 'Inasubiri',
    startChat: 'Anza Mazungumzo',
    chat: 'Ongea',
    requestSent: 'Ombi la urafiki limetumwa',
    pendingIncoming: 'Inasubiri — kubali kama rafiki',
    pendingOutgoing: 'Maombi Yaliyotumwa',
    yourFriends: 'Marafiki wako',
    wantsToBeFriend: 'Anataka kuwa rafiki yako',
    waitingForAccept: 'Unasubiri akubali',
    waitingForResponse: 'Inasubiri majibu',
    noPendingRequests: 'Hakuna maombi ya urafiki yanayosubiri',
    searchHint: 'Andika angalau herufi 2 kutafuta',
    cancelRequest: 'Ghairi',
  },
  notifications: {
    title: 'Arifa',
    unread: 'zisizosomwa',
    markAllRead: 'Weka zote zimesomwa',
    empty: 'Hakuna arifa bado',
    pullUp: 'Vuta juu kwa skrini nzima',
    pullDown: 'Vuta chini kupunguza',
    friendRequest: 'Ombi la urafiki',
    friendAccepted: 'Urafiki umekubaliwa',
    newMessage: 'Ujumbe mpya',
  },
  profile: {
    title: 'Wasifu',
    edit: 'Hariri Wasifu',
    bio: 'Wasifu',
    status: 'Hali',
    save: 'Hifadhi',
    cancel: 'Ghairi',
    personalInfo: 'Taarifa Binafsi',
    education: 'Elimu',
    viewAllUniversities: 'Angalia vyuo vyote',
    privateInfo: 'Taarifa Faragha',
    accountInfo: 'Akaunti',
    mobileNumber: 'Nambari ya Simu',
    memberSince: 'Mwanachama Tangu',
    onlineStatus: 'Hali',
    verified: 'Imethibitishwa',
    privateOnly: 'Inaonekana kwako tu',
    noChanges: 'Hakuna mabadiliko ya kuhifadhi',
    saved: 'Wasifu umesasishwa',
    mobileHint: 'Muundo wa kimataifa mfano +254712345678',
    friendsCount: 'Marafiki',
    pendingRequests: 'Maombi Yanayosubiri',
    sentRequests: 'Maombi Yaliyotumwa',
    changePhoto: 'Badilisha Picha ya Wasifu',
    removePhoto: 'Ondoa Picha ya Wasifu',
    removePhotoConfirm: 'Unataka kuondoa picha yako maalum na kuchagua avatar ya AO Chats?',
    photoPreview: 'Hakiki',
    photoSaved: 'Picha ya wasifu imehifadhiwa',
    photoRemoved: 'Picha imeondolewa — chagua avatar',
    photoFailed: 'Imeshindwa kusasisha picha ya wasifu',
    photoSaveFailed: 'Picha ya wasifu haikuweza kuhifadhiwa. Jaribu tena.',
    useAoAvatar: 'Avatari za AO',
    chooseAvatar: 'Chagua avatar yako ya wasifu',
    photoMenuTitle: 'Picha ya Wasifu',
    viewProfilePhoto: 'Angalia Wasifu',
  },
  friendInfo: {
    title: 'Taarifa za Rafiki',
    message: 'Ujumbe',
    conversation: 'Mazungumzo',
    sharedMedia: 'Media Iliyoshirikiwa',
    photos: 'Picha',
    videos: 'Video',
    documents: 'Nyaraka',
    links: 'Viungo',
    privacy: 'Faragha',
    block: 'Zuia',
    blockConfirm: 'Unataka kumzuia mtumiaji huyu? Hamtaweza kupeana ujumbe.',
    clearChat: 'Futa Mazungumzo',
    clearChatConfirm: 'Unataka kufuta ujumbe wote kwenye chat hii kwako? Huwezi kurudisha.',
    deleteChat: 'Futa Kutoka Orodha',
    deleteChatConfirm: 'Unataka kuondoa mazungumzo haya kwenye orodha yako?',
    offlineCached: 'Inaonyesha wasifu uliohifadhiwa',
    emptyMedia: 'Hakuna media iliyoshirikiwa bado',
    sharedOn: 'Imeshirikiwa',
    openLink: 'Fungua',
    copyLink: 'Nakili',
    networkRequired: 'Unganisha mtandao ili kupakia media hii.',
  },
  settings: {
    title: 'Mipangilio',
    theme: 'Mandhari',
    light: 'Nuru',
    dark: 'Giza',
    language: 'Lugha',
    english: 'Kiingereza',
    swahili: 'Kiswahili',
    fontSize: 'Ukubwa wa Herufi',
    small: 'Ndogo',
    medium: 'Wastani',
    large: 'Kubwa',
    privacy: 'Faragha',
    blockedUsers: 'Watumiaji Waliozuiliwa',
    logout: 'Toka',
    logoutConfirm: 'Una uhakika unataka kutoka?',
    notifications: 'Arifa',
    support: 'Msaada',
    aoManager: 'Ongea na AO Manager',
    aoManagerDesc: 'Msaada Rasmi wa AO Chats',
    aoManagerUnavailable: 'AO Manager haipatikani kwa sasa. Jaribu tena.',
    universitiesDirectory: 'Vyuo vikuu Tanzania',
    viewAllUniversities: 'Angalia vyuo vyote',
    searchUniversities: 'Tafuta kwa jina, kifupi, au eneo',
    universityAbbreviation: 'Kifupi',
    universityLocation: 'Eneo',
    noUniversitiesMatch: 'Hakuna chuo kinacholingana na utafutaji wako',
    sounds: 'Sauti na Mtetemo',
    chatSound: 'Sauti ya Mazungumzo',
    chatVibration: 'Mtetemo wa Mazungumzo',
    notificationSound: 'Sauti ya Arifa',
    notificationVibration: 'Mtetemo wa Arifa',
  },
  common: {
    loading: 'Inapakia...',
    error: 'Kuna tatizo limetokea',
    retry: 'Jaribu tena',
    cancel: 'Ghairi',
    confirm: 'Thibitisha',
    save: 'Hifadhi',
    delete: 'Futa',
    search: 'Tafuta',
    noResults: 'Hakuna matokeo',
  },
  tabs: { chats: 'Mazungumzo', friends: 'Marafiki', profile: 'Wasifu', settings: 'Mipangilio' },
};

export type Translations = typeof en;
